### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ngodink** [kolirt/laravel-cross-domain-session#1]
Give tutorial about using this library.. I've been following the installation, but its not affected to my multiple project. Thanks.

**Comment by kolirt** [comment]
> Give tutorial about using this library.. I've been following the installation, but its not affected to my multiple project. Thanks.

Can you tell more about your problem?

**Comment by ngodink** [comment]
I have two project of laravel, call it ``laravel1.dev`` (laravel with manual authentication application) and ``laravel2.test`` (laravel as application). I want to make it like google account with youtube, which share the session from ``laravel1.test`` to another my domain that i've listed in ``config/cross-domain-session``..

Example: I have been logged in from laravel1.dev, so i refresh from laravel2.dev, so, should have been an automatic login..

**Comment by kolirt** [comment]
> I have two project of laravel, call it `laravel1.test` (laravel with manual authentication application) and `laravel2.test` (laravel as application). I want to make it like google account with youtube, which share the session from `laravel1.test` to another my domain that i've listed in `config/cross-domain-session`..
> 
> Example: I have been logged in from laravel1.test, so i refresh from laravel2.test, so, should have been an automatic login..

I made this package to synchronize data between domains using the cd_domain helper. I used this package to synchronize the shopping cart. I think that you need to change the logic of authorization and make it work with the cd_domain helper. But I think it's not safe (but it seems Google does that)
